# Generated by Django 3.0.4 on 2020-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File',
            field=models.FileField(upload_to='C:/Users/saura/Desktop/Major/Major_Project'),
        ),
    ]
